import { MessageFieldDef } from './interface';

const MsgDefs: {[k: string]: MessageFieldDef} = {
  'file_id': {
    'num': 0,
    'fields': [{
      'name': 'type',
      'number': 0,
      'type': 'file',
      'scale': null,
      'offset': null,
      'units': ''
    }, {
      'name': 'manufacturer',
      'number': 1,
      'type': 'manufacturer',
      'scale': null,
      'offset': null,
      'units': ''
    }, {
      'name': 'product',
      'number': 2,
      'type': 'uint16',
      'scale': null,
      'offset': null,
      'units': ''
    }, {
      'name': 'serial_number',
      'number': 3,
      'type': 'uint32z',
      'scale': null,
      'offset': null,
      'units': ''
    }, {
      'name': 'time_created',
      'number': 4,
      'type': 'date_time',
      'scale': null,
      'offset': null,
      'units': ''
    }, {
      'name': 'number',
      'number': 5,
      'type': 'uint16',
      'scale': null,
      'offset': null,
      'units': ''
    }, { 'name': 'product_name', 'number': 8, 'type': 'string', 'scale': null, 'offset': null, 'units': '' }]
  },
  'capabilities': {
    'num': 1,
    'fields': [{
      'name': 'languages',
      'number': 0,
      'type': 'uint8z',
      'scale': null,
      'offset': null,
      'units': ''
    }, {
      'name': 'sports',
      'number': 1,
      'type': 'sport_bits_0',
      'scale': null,
      'offset': null,
      'units': ''
    }, {
      'name': 'workouts_supported',
      'number': 21,
      'type': 'workout_capabilities',
      'scale': null,
      'offset': null,
      'units': ''
    }, {
      'name': 'connectivity_supported',
      'number': 23,
      'type': 'connectivity_capabilities',
      'scale': null,
      'offset': null,
      'units': ''
    }]
  },
  'device_settings': {
    'num': 2,
    'fields': [{
      'name': 'active_time_zone',
      'number': 0,
      'type': 'uint8',
      'scale': null,
      'offset': null,
      'units': ''
    }, {
      'name': 'utc_offset',
      'number': 1,
      'type': 'uint32',
      'scale': null,
      'offset': null,
      'units': ''
    }, {
      'name': 'time_offset',
      'number': 2,
      'type': 'uint32',
      'scale': null,
      'offset': null,
      'units': 's'
    }, {
      'name': 'time_zone_offset',
      'number': 5,
      'type': 'sint8',
      'scale': 4,
      'offset': null,
      'units': 'hr'
    }, {
      'name': 'display_orientation',
      'number': 55,
      'type': 'display_orientation',
      'scale': null,
      'offset': null,
      'units': ''
    }, {
      'name': 'mounting_side',
      'number': 56,
      'type': 'side',
      'scale': null,
      'offset': null,
      'units': ''
    }, {
      'name': 'number_of_screens',
      'number': 94,
      'type': 'uint8',
      'scale': null,
      'offset': null,
      'units': ''
    }, {
      'name': 'smart_notification_display_orientation',
      'number': 95,
      'type': 'display_orientation',
      'scale': null,
      'offset': null,
      'units': ''
    }]
  },
  'user_profile': {
    'num': 3,
    'fields': [{
      'name': 'friendly_name',
      'number': 0,
      'type': 'string',
      'scale': null,
      'offset': 0,
      'units': ''
    }, { 'name': 'gender', 'number': 1, 'type': 'gender', 'scale': null, 'offset': 0, 'units': '' }, {
      'name': 'age',
      'number': 2,
      'type': 'uint8',
      'scale': null,
      'offset': 0,
      'units': 'years'
    }, { 'name': 'height', 'number': 3, 'type': 'uint8', 'scale': 100, 'offset': 0, 'units': 'm' }, {
      'name': 'weight',
      'number': 4,
      'type': 'uint16',
      'scale': 10,
      'offset': 0,
      'units': 'kg'
    }, {
      'name': 'language',
      'number': 5,
      'type': 'language',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'elev_setting',
      'number': 6,
      'type': 'display_measure',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'weight_setting',
      'number': 7,
      'type': 'display_measure',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'resting_heart_rate',
      'number': 8,
      'type': 'uint8',
      'scale': null,
      'offset': 0,
      'units': 'bpm'
    }, {
      'name': 'default_max_running_heart_rate',
      'number': 9,
      'type': 'uint8',
      'scale': null,
      'offset': 0,
      'units': 'bpm'
    }, {
      'name': 'default_max_biking_heart_rate',
      'number': 10,
      'type': 'uint8',
      'scale': null,
      'offset': 0,
      'units': 'bpm'
    }, {
      'name': 'default_max_heart_rate',
      'number': 11,
      'type': 'uint8',
      'scale': null,
      'offset': 0,
      'units': 'bpm'
    }, {
      'name': 'hr_setting',
      'number': 12,
      'type': 'display_heart',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'speed_setting',
      'number': 13,
      'type': 'display_measure',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'dist_setting',
      'number': 14,
      'type': 'display_measure',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'power_setting',
      'number': 16,
      'type': 'display_power',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'activity_class',
      'number': 17,
      'type': 'activity_class',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'position_setting',
      'number': 18,
      'type': 'display_position',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'temperature_setting',
      'number': 21,
      'type': 'display_measure',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'local_id',
      'number': 22,
      'type': 'user_local_id',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'global_id',
      'number': 23,
      'type': 'byte',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'height_setting',
      'number': 30,
      'type': 'display_measure',
      'scale': null,
      'offset': 0,
      'units': ''
    }, { 'name': 'message_index', 'number': 254, 'type': 'message_index', 'scale': null, 'offset': 0, 'units': '' }]
  },
  'hrm_profile': {
    'num': 4,
    'fields': [{
      'name': 'enabled',
      'number': 0,
      'type': 'bool',
      'scale': null,
      'offset': null,
      'units': ''
    }, {
      'name': 'hrm_ant_id',
      'number': 1,
      'type': 'uint16z',
      'scale': null,
      'offset': null,
      'units': ''
    }, {
      'name': 'log_hrv',
      'number': 2,
      'type': 'bool',
      'scale': null,
      'offset': null,
      'units': ''
    }, {
      'name': 'hrm_ant_id_trans_type',
      'number': 3,
      'type': 'uint8z',
      'scale': null,
      'offset': null,
      'units': ''
    }, { 'name': 'message_index', 'number': 254, 'type': 'message_index', 'scale': null, 'offset': null, 'units': '' }]
  },
  'sdm_profile': {
    'num': 5,
    'fields': [{
      'name': 'enabled',
      'number': 0,
      'type': 'bool',
      'scale': null,
      'offset': null,
      'units': ''
    }, {
      'name': 'sdm_ant_id',
      'number': 1,
      'type': 'uint16z',
      'scale': null,
      'offset': null,
      'units': ''
    }, {
      'name': 'sdm_cal_factor',
      'number': 2,
      'type': 'uint16',
      'scale': 10,
      'offset': null,
      'units': '%'
    }, {
      'name': 'odometer',
      'number': 3,
      'type': 'uint32',
      'scale': 100,
      'offset': null,
      'units': 'm'
    }, {
      'name': 'speed_source',
      'number': 4,
      'type': 'bool',
      'scale': null,
      'offset': null,
      'units': ''
    }, {
      'name': 'sdm_ant_id_trans_type',
      'number': 5,
      'type': 'uint8z',
      'scale': null,
      'offset': null,
      'units': ''
    }, {
      'name': 'odometer_rollover',
      'number': 7,
      'type': 'uint8',
      'scale': null,
      'offset': null,
      'units': ''
    }, { 'name': 'message_index', 'number': 254, 'type': 'message_index', 'scale': null, 'offset': null, 'units': '' }]
  },
  'bike_profile': {
    'num': 6,
    'fields': [{
      'name': 'name',
      'number': 0,
      'type': 'string',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'sport',
      'number': 1,
      'type': 'sport',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'sub_sport',
      'number': 2,
      'type': 'sub_sport',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'odometer',
      'number': 3,
      'type': 'uint32',
      'scale': 100,
      'offset': 0,
      'units': 'm'
    }, {
      'name': 'bike_spd_ant_id',
      'number': 4,
      'type': 'uint16z',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'bike_cad_ant_id',
      'number': 5,
      'type': 'uint16z',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'bike_spdcad_ant_id',
      'number': 6,
      'type': 'uint16z',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'bike_power_ant_id',
      'number': 7,
      'type': 'uint16z',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'custom_wheelsize',
      'number': 8,
      'type': 'uint16',
      'scale': 1000,
      'offset': 0,
      'units': 'm'
    }, {
      'name': 'auto_wheelsize',
      'number': 9,
      'type': 'uint16',
      'scale': 1000,
      'offset': 0,
      'units': 'm'
    }, {
      'name': 'bike_weight',
      'number': 10,
      'type': 'uint16',
      'scale': 10,
      'offset': 0,
      'units': 'kg'
    }, {
      'name': 'power_cal_factor',
      'number': 11,
      'type': 'uint16',
      'scale': 10,
      'offset': 0,
      'units': '%'
    }, {
      'name': 'auto_wheel_cal',
      'number': 12,
      'type': 'bool',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'auto_power_zero',
      'number': 13,
      'type': 'bool',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'id',
      'number': 14,
      'type': 'uint8',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'spd_enabled',
      'number': 15,
      'type': 'bool',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'cad_enabled',
      'number': 16,
      'type': 'bool',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'spdcad_enabled',
      'number': 17,
      'type': 'bool',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'power_enabled',
      'number': 18,
      'type': 'bool',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'crank_length',
      'number': 19,
      'type': 'uint8',
      'scale': 2,
      'offset': -110,
      'units': 'mm'
    }, {
      'name': 'enabled',
      'number': 20,
      'type': 'bool',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'bike_spd_ant_id_trans_type',
      'number': 21,
      'type': 'uint8z',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'bike_cad_ant_id_trans_type',
      'number': 22,
      'type': 'uint8z',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'bike_spdcad_ant_id_trans_type',
      'number': 23,
      'type': 'uint8z',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'bike_power_ant_id_trans_type',
      'number': 24,
      'type': 'uint8z',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'odometer_rollover',
      'number': 37,
      'type': 'uint8',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'front_gear_num',
      'number': 38,
      'type': 'uint8z',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'front_gear',
      'number': 39,
      'type': 'uint8z',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'rear_gear_num',
      'number': 40,
      'type': 'uint8z',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'rear_gear',
      'number': 41,
      'type': 'uint8z',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'shimano_di2_enabled',
      'number': 44,
      'type': 'bool',
      'scale': null,
      'offset': 0,
      'units': ''
    }, { 'name': 'message_index', 'number': 254, 'type': 'message_index', 'scale': null, 'offset': 0, 'units': '' }]
  },
  'zones_target': {
    'num': 7,
    'fields': [{
      'name': 'max_heart_rate',
      'number': 1,
      'type': 'uint8',
      'scale': null,
      'offset': null,
      'units': ''
    }, {
      'name': 'threshold_heart_rate',
      'number': 2,
      'type': 'uint8',
      'scale': null,
      'offset': null,
      'units': ''
    }, {
      'name': 'functional_threshold_power',
      'number': 3,
      'type': 'uint16',
      'scale': null,
      'offset': null,
      'units': ''
    }, {
      'name': 'hr_calc_type',
      'number': 5,
      'type': 'hr_zone_calc',
      'scale': null,
      'offset': null,
      'units': ''
    }, { 'name': 'pwr_calc_type', 'number': 7, 'type': 'pwr_zone_calc', 'scale': null, 'offset': null, 'units': '' }]
  },
  'hr_zone': {
    'num': 8,
    'fields': [{
      'name': 'high_bpm',
      'number': 1,
      'type': 'uint8',
      'scale': null,
      'offset': 0,
      'units': 'bpm'
    }, {
      'name': 'name',
      'number': 2,
      'type': 'string',
      'scale': null,
      'offset': 0,
      'units': ''
    }, { 'name': 'message_index', 'number': 254, 'type': 'message_index', 'scale': null, 'offset': 0, 'units': '' }]
  },
  'power_zone': {
    'num': 9,
    'fields': [{
      'name': 'high_value',
      'number': 1,
      'type': 'uint16',
      'scale': null,
      'offset': 0,
      'units': 'watts'
    }, {
      'name': 'name',
      'number': 2,
      'type': 'string',
      'scale': null,
      'offset': 0,
      'units': ''
    }, { 'name': 'message_index', 'number': 254, 'type': 'message_index', 'scale': null, 'offset': 0, 'units': '' }]
  },
  'met_zone': {
    'num': 10,
    'fields': [{
      'name': 'high_bpm',
      'number': 1,
      'type': 'uint8',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'calories',
      'number': 2,
      'type': 'uint16',
      'scale': 10,
      'offset': 0,
      'units': 'kcal / min'
    }, {
      'name': 'fat_calories',
      'number': 3,
      'type': 'uint8',
      'scale': 10,
      'offset': 0,
      'units': 'kcal / min'
    }, { 'name': 'message_index', 'number': 254, 'type': 'message_index', 'scale': null, 'offset': 0, 'units': '' }]
  },
  'sport': {
    'num': 12,
    'fields': [{
      'name': 'sport',
      'number': 0,
      'type': 'sport',
      'scale': null,
      'offset': null,
      'units': ''
    }, {
      'name': 'sub_sport',
      'number': 1,
      'type': 'sub_sport',
      'scale': null,
      'offset': null,
      'units': ''
    }, { 'name': 'name', 'number': 3, 'type': 'string', 'scale': null, 'offset': null, 'units': '' }]
  },
  'goal': {
    'num': 15,
    'fields': [{
      'name': 'sport',
      'number': 0,
      'type': 'sport',
      'scale': null,
      'offset': null,
      'units': ''
    }, {
      'name': 'sub_sport',
      'number': 1,
      'type': 'sub_sport',
      'scale': null,
      'offset': null,
      'units': ''
    }, {
      'name': 'start_date',
      'number': 2,
      'type': 'date_time',
      'scale': null,
      'offset': null,
      'units': ''
    }, {
      'name': 'end_date',
      'number': 3,
      'type': 'date_time',
      'scale': null,
      'offset': null,
      'units': ''
    }, { 'name': 'type', 'number': 4, 'type': 'goal', 'scale': null, 'offset': null, 'units': '' }, {
      'name': 'value',
      'number': 5,
      'type': 'uint32',
      'scale': null,
      'offset': null,
      'units': ''
    }, {
      'name': 'repeat',
      'number': 6,
      'type': 'bool',
      'scale': null,
      'offset': null,
      'units': ''
    }, {
      'name': 'target_value',
      'number': 7,
      'type': 'uint32',
      'scale': null,
      'offset': null,
      'units': ''
    }, {
      'name': 'recurrence',
      'number': 8,
      'type': 'goal_recurrence',
      'scale': null,
      'offset': null,
      'units': ''
    }, {
      'name': 'recurrence_value',
      'number': 9,
      'type': 'uint16',
      'scale': null,
      'offset': null,
      'units': ''
    }, {
      'name': 'enabled',
      'number': 10,
      'type': 'bool',
      'scale': null,
      'offset': null,
      'units': ''
    }, { 'name': 'message_index', 'number': 254, 'type': 'message_index', 'scale': null, 'offset': null, 'units': '' }]
  },
  'session': {
    'num': 18,
    'fields': [{
      'name': 'event',
      'number': 0,
      'type': 'event',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'event_type',
      'number': 1,
      'type': 'event_type',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'start_time',
      'number': 2,
      'type': 'date_time',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'start_position_lat',
      'number': 3,
      'type': 'sint32',
      'scale': null,
      'offset': 0,
      'units': 'semicircles'
    }, {
      'name': 'start_position_long',
      'number': 4,
      'type': 'sint32',
      'scale': null,
      'offset': 0,
      'units': 'semicircles'
    }, {
      'name': 'sport',
      'number': 5,
      'type': 'sport',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'sub_sport',
      'number': 6,
      'type': 'sub_sport',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'total_elapsed_time',
      'number': 7,
      'type': 'uint32',
      'scale': 1000,
      'offset': 0,
      'units': 's'
    }, {
      'name': 'total_timer_time',
      'number': 8,
      'type': 'uint32',
      'scale': 1000,
      'offset': 0,
      'units': 's'
    }, {
      'name': 'total_distance',
      'number': 9,
      'type': 'uint32',
      'scale': 100,
      'offset': 0,
      'units': 'm'
    }, {
      'name': 'total_cycles',
      'number': 10,
      'type': 'uint32',
      'scale': null,
      'offset': 0,
      'units': 'cycles'
    }, {
      'name': 'total_calories',
      'number': 11,
      'type': 'uint16',
      'scale': null,
      'offset': 0,
      'units': 'kcal'
    }, {
      'name': 'total_fat_calories',
      'number': 13,
      'type': 'uint16',
      'scale': null,
      'offset': 0,
      'units': 'kcal'
    }, {
      'name': 'avg_speed',
      'number': 14,
      'type': 'uint16',
      'scale': 1000,
      'offset': 0,
      'units': 'm/s'
    }, {
      'name': 'max_speed',
      'number': 15,
      'type': 'uint16',
      'scale': 1000,
      'offset': 0,
      'units': 'm/s'
    }, {
      'name': 'avg_heart_rate',
      'number': 16,
      'type': 'uint8',
      'scale': null,
      'offset': 0,
      'units': 'bpm'
    }, {
      'name': 'max_heart_rate',
      'number': 17,
      'type': 'uint8',
      'scale': null,
      'offset': 0,
      'units': 'bpm'
    }, {
      'name': 'avg_cadence',
      'number': 18,
      'type': 'uint8',
      'scale': null,
      'offset': 0,
      'units': 'rpm'
    }, {
      'name': 'max_cadence',
      'number': 19,
      'type': 'uint8',
      'scale': null,
      'offset': 0,
      'units': 'rpm'
    }, {
      'name': 'avg_power',
      'number': 20,
      'type': 'uint16',
      'scale': null,
      'offset': 0,
      'units': 'watts'
    }, {
      'name': 'max_power',
      'number': 21,
      'type': 'uint16',
      'scale': null,
      'offset': 0,
      'units': 'watts'
    }, {
      'name': 'total_ascent',
      'number': 22,
      'type': 'uint16',
      'scale': null,
      'offset': 0,
      'units': 'm'
    }, {
      'name': 'total_descent',
      'number': 23,
      'type': 'uint16',
      'scale': null,
      'offset': 0,
      'units': 'm'
    }, {
      'name': 'total_training_effect',
      'number': 24,
      'type': 'uint8',
      'scale': 10,
      'offset': 0,
      'units': ''
    }, {
      'name': 'first_lap_index',
      'number': 25,
      'type': 'uint16',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'num_laps',
      'number': 26,
      'type': 'uint16',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'event_group',
      'number': 27,
      'type': 'uint8',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'trigger',
      'number': 28,
      'type': 'session_trigger',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'nec_lat',
      'number': 29,
      'type': 'sint32',
      'scale': null,
      'offset': 0,
      'units': 'semicircles'
    }, {
      'name': 'nec_long',
      'number': 30,
      'type': 'sint32',
      'scale': null,
      'offset': 0,
      'units': 'semicircles'
    }, {
      'name': 'swc_lat',
      'number': 31,
      'type': 'sint32',
      'scale': null,
      'offset': 0,
      'units': 'semicircles'
    }, {
      'name': 'swc_long',
      'number': 32,
      'type': 'sint32',
      'scale': null,
      'offset': 0,
      'units': 'semicircles'
    }, {
      'name': 'normalized_power',
      'number': 34,
      'type': 'uint16',
      'scale': null,
      'offset': 0,
      'units': 'watts'
    }, {
      'name': 'training_stress_score',
      'number': 35,
      'type': 'uint16',
      'scale': 10,
      'offset': 0,
      'units': 'tss'
    }, {
      'name': 'intensity_factor',
      'number': 36,
      'type': 'uint16',
      'scale': 1000,
      'offset': 0,
      'units': 'if'
    }, {
      'name': 'left_right_balance',
      'number': 37,
      'type': 'left_right_balance_100',
      'scale': 100,
      'offset': 0,
      'units': '%'
    }, {
      'name': 'avg_stroke_count',
      'number': 41,
      'type': 'uint32',
      'scale': 10,
      'offset': 0,
      'units': 'strokes/lap'
    }, {
      'name': 'avg_stroke_distance',
      'number': 42,
      'type': 'uint16',
      'scale': 100,
      'offset': 0,
      'units': 'm'
    }, {
      'name': 'swim_stroke',
      'number': 43,
      'type': 'swim_stroke',
      'scale': null,
      'offset': 0,
      'units': 'swim_stroke'
    }, {
      'name': 'pool_length',
      'number': 44,
      'type': 'uint16',
      'scale': 100,
      'offset': 0,
      'units': 'm'
    }, {
      'name': 'threshold_power',
      'number': 45,
      'type': 'uint16',
      'scale': null,
      'offset': 0,
      'units': 'watts'
    }, {
      'name': 'pool_length_unit',
      'number': 46,
      'type': 'display_measure',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'num_active_lengths',
      'number': 47,
      'type': 'uint16',
      'scale': null,
      'offset': 0,
      'units': 'lengths'
    }, {
      'name': 'total_work',
      'number': 48,
      'type': 'uint32',
      'scale': null,
      'offset': 0,
      'units': 'J'
    }, {
      'name': 'avg_altitude',
      'number': 49,
      'type': 'uint16',
      'scale': 5,
      'offset': -500,
      'units': 'm'
    }, {
      'name': 'max_altitude',
      'number': 50,
      'type': 'uint16',
      'scale': 5,
      'offset': -500,
      'units': 'm'
    }, {
      'name': 'gps_accuracy',
      'number': 51,
      'type': 'uint8',
      'scale': null,
      'offset': 0,
      'units': 'm'
    }, {
      'name': 'avg_grade',
      'number': 52,
      'type': 'sint16',
      'scale': 100,
      'offset': 0,
      'units': '%'
    }, {
      'name': 'avg_pos_grade',
      'number': 53,
      'type': 'sint16',
      'scale': 100,
      'offset': 0,
      'units': '%'
    }, {
      'name': 'avg_neg_grade',
      'number': 54,
      'type': 'sint16',
      'scale': 100,
      'offset': 0,
      'units': '%'
    }, {
      'name': 'max_pos_grade',
      'number': 55,
      'type': 'sint16',
      'scale': 100,
      'offset': 0,
      'units': '%'
    }, {
      'name': 'max_neg_grade',
      'number': 56,
      'type': 'sint16',
      'scale': 100,
      'offset': 0,
      'units': '%'
    }, {
      'name': 'avg_temperature',
      'number': 57,
      'type': 'sint8',
      'scale': null,
      'offset': 0,
      'units': 'C'
    }, {
      'name': 'max_temperature',
      'number': 58,
      'type': 'sint8',
      'scale': null,
      'offset': 0,
      'units': 'C'
    }, {
      'name': 'total_moving_time',
      'number': 59,
      'type': 'uint32',
      'scale': 1000,
      'offset': 0,
      'units': 's'
    }, {
      'name': 'avg_pos_vertical_speed',
      'number': 60,
      'type': 'uint16',
      'scale': 1000,
      'offset': 0,
      'units': 'm/s'
    }, {
      'name': 'avg_neg_vertical_speed',
      'number': 61,
      'type': 'uint16',
      'scale': 1000,
      'offset': 0,
      'units': 'm/s'
    }, {
      'name': 'max_pos_vertical_speed',
      'number': 62,
      'type': 'uint16',
      'scale': 1000,
      'offset': 0,
      'units': 'm/s'
    }, {
      'name': 'max_neg_vertical_speed',
      'number': 63,
      'type': 'uint16',
      'scale': 1000,
      'offset': 0,
      'units': 'm/s'
    }, {
      'name': 'min_heart_rate',
      'number': 64,
      'type': 'uint8',
      'scale': null,
      'offset': 0,
      'units': 'bpm'
    }, {
      'name': 'time_in_hr_zone',
      'number': 65,
      'type': 'uint32_array',
      'scale': 1000,
      'offset': 0,
      'units': 's'
    }, {
      'name': 'time_in_speed_zone',
      'number': 66,
      'type': 'uint32_array',
      'scale': 1000,
      'offset': 0,
      'units': 's'
    }, {
      'name': 'time_in_cadence_zone',
      'number': 67,
      'type': 'uint32_array',
      'scale': 1000,
      'offset': 0,
      'units': 's'
    }, {
      'name': 'time_in_power_zone',
      'number': 68,
      'type': 'uint32_array',
      'scale': 1000,
      'offset': 0,
      'units': 's'
    }, {
      'name': 'avg_lap_time',
      'number': 69,
      'type': 'uint32',
      'scale': 1000,
      'offset': 0,
      'units': 's'
    }, {
      'name': 'best_lap_index',
      'number': 70,
      'type': 'uint16',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'min_altitude',
      'number': 71,
      'type': 'uint16',
      'scale': 5,
      'offset': -500,
      'units': 'm'
    }, {
      'name': 'player_score',
      'number': 82,
      'type': 'uint16',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'opponent_score',
      'number': 83,
      'type': 'uint16',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'opponent_name',
      'number': 84,
      'type': 'string',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'stroke_count',
      'number': 85,
      'type': 'uint16',
      'scale': null,
      'offset': 0,
      'units': 'counts'
    }, {
      'name': 'zone_count',
      'number': 86,
      'type': 'uint16',
      'scale': null,
      'offset': 0,
      'units': 'counts'
    }, {
      'name': 'max_ball_speed',
      'number': 87,
      'type': 'uint16',
      'scale': 100,
      'offset': 0,
      'units': 'm/s'
    }, {
      'name': 'avg_ball_speed',
      'number': 88,
      'type': 'uint16',
      'scale': 100,
      'offset': 0,
      'units': 'm/s'
    }, {
      'name': 'avg_vertical_oscillation',
      'number': 89,
      'type': 'uint16',
      'scale': 10,
      'offset': 0,
      'units': 'mm'
    }, {
      'name': 'avg_stance_time_percent',
      'number': 90,
      'type': 'uint16',
      'scale': 100,
      'offset': 0,
      'units': 'percent'
    }, {
      'name': 'avg_stance_time',
      'number': 91,
      'type': 'uint16',
      'scale': 10,
      'offset': 0,
      'units': 'ms'
    }, {
      'name': 'avg_fractional_cadence',
      'number': 92,
      'type': 'uint8',
      'scale': 128,
      'offset': 0,
      'units': 'rpm'
    }, {
      'name': 'max_fractional_cadence',
      'number': 93,
      'type': 'uint8',
      'scale': 128,
      'offset': 0,
      'units': 'rpm'
    }, {
      'name': 'total_fractional_cycles',
      'number': 94,
      'type': 'uint8',
      'scale': 128,
      'offset': 0,
      'units': 'cycles'
    }, {
      'name': 'avg_total_hemoglobin_conc',
      'number': 95,
      'type': 'uint16',
      'scale': 100,
      'offset': 0,
      'units': 'g/dL'
    }, {
      'name': 'min_total_hemoglobin_conc',
      'number': 96,
      'type': 'uint16',
      'scale': 100,
      'offset': 0,
      'units': 'g/dL'
    }, {
      'name': 'max_total_hemoglobin_conc',
      'number': 97,
      'type': 'uint16',
      'scale': 100,
      'offset': 0,
      'units': 'g/dL'
    }, {
      'name': 'avg_saturated_hemoglobin_percent',
      'number': 98,
      'type': 'uint16',
      'scale': 10,
      'offset': 0,
      'units': '%'
    }, {
      'name': 'min_saturated_hemoglobin_percent',
      'number': 99,
      'type': 'uint16',
      'scale': 10,
      'offset': 0,
      'units': '%'
    }, {
      'name': 'max_saturated_hemoglobin_percent',
      'number': 100,
      'type': 'uint16',
      'scale': 10,
      'offset': 0,
      'units': '%'
    }, {
      'name': 'avg_left_torque_effectiveness',
      'number': 101,
      'type': 'uint8',
      'scale': 2,
      'offset': 0,
      'units': 'percent'
    }, {
      'name': 'avg_right_torque_effectiveness',
      'number': 102,
      'type': 'uint8',
      'scale': 2,
      'offset': 0,
      'units': 'percent'
    }, {
      'name': 'avg_left_pedal_smoothness',
      'number': 103,
      'type': 'uint8',
      'scale': 2,
      'offset': 0,
      'units': 'percent'
    }, {
      'name': 'avg_right_pedal_smoothness',
      'number': 104,
      'type': 'uint8',
      'scale': 2,
      'offset': 0,
      'units': 'percent'
    }, {
      'name': 'avg_combined_pedal_smoothness',
      'number': 105,
      'type': 'uint8',
      'scale': 2,
      'offset': 0,
      'units': 'percent'
    }, {
      'name': 'sport_index',
      'number': 111,
      'type': 'uint8',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'time_standing',
      'number': 112,
      'type': 'uint32',
      'scale': 1000,
      'offset': 0,
      'units': 's'
    }, {
      'name': 'stand_count',
      'number': 113,
      'type': 'uint16',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'avg_left_pco',
      'number': 114,
      'type': 'sint8',
      'scale': null,
      'offset': 0,
      'units': 'mm'
    }, {
      'name': 'avg_right_pco',
      'number': 115,
      'type': 'sint8',
      'scale': null,
      'offset': 0,
      'units': 'mm'
    }, {
      'name': 'avg_left_power_phase',
      'number': 116,
      'type': 'uint8',
      'scale': null,
      'offset': 0,
      'units': 'degrees'
    }, {
      'name': 'avg_left_power_phase_peak',
      'number': 117,
      'type': 'uint8',
      'scale': null,
      'offset': 0,
      'units': 'degrees'
    }, {
      'name': 'avg_right_power_phase',
      'number': 118,
      'type': 'uint8',
      'scale': null,
      'offset': 0,
      'units': 'degrees'
    }, {
      'name': 'avg_right_power_phase_peak',
      'number': 119,
      'type': 'uint8',
      'scale': null,
      'offset': 0,
      'units': 'degrees'
    }, {
      'name': 'avg_power_position',
      'number': 120,
      'type': 'uint16',
      'scale': null,
      'offset': 0,
      'units': 'watts'
    }, {
      'name': 'max_power_position',
      'number': 121,
      'type': 'uint16',
      'scale': null,
      'offset': 0,
      'units': 'watts'
    }, {
      'name': 'avg_cadence_position',
      'number': 122,
      'type': 'uint8',
      'scale': null,
      'offset': 0,
      'units': 'rpm'
    }, {
      'name': 'max_cadence_position',
      'number': 123,
      'type': 'uint8',
      'scale': null,
      'offset': 0,
      'units': 'rpm'
    }, {
      'name': 'enhanced_avg_speed',
      'number': 124,
      'type': 'uint32',
      'scale': 1000,
      'offset': 0,
      'units': 'm/s'
    }, {
      'name': 'enhanced_max_speed',
      'number': 125,
      'type': 'uint32',
      'scale': 1000,
      'offset': 0,
      'units': 'm/s'
    }, {
      'name': 'enhanced_avg_altitude',
      'number': 126,
      'type': 'uint32',
      'scale': 5,
      'offset': -500,
      'units': 'm'
    }, {
      'name': 'enhanced_min_altitude',
      'number': 127,
      'type': 'uint32',
      'scale': 5,
      'offset': -500,
      'units': 'm'
    }, {
      'name': 'enhanced_max_altitude',
      'number': 128,
      'type': 'uint32',
      'scale': 5,
      'offset': -500,
      'units': 'm'
    }, {
      'name': 'avg_lev_motor_power',
      'number': 129,
      'type': 'uint16',
      'scale': null,
      'offset': 0,
      'units': 'watts'
    }, {
      'name': 'max_lev_motor_power',
      'number': 130,
      'type': 'uint16',
      'scale': null,
      'offset': 0,
      'units': 'watts'
    }, {
      'name': 'lev_battery_consumption',
      'number': 131,
      'type': 'uint8',
      'scale': 2,
      'offset': 0,
      'units': 'percent'
    }, {
      'name': 'avg_vertical_ratio',
      'number': 132,
      'type': 'uint16',
      'scale': 100,
      'offset': 0,
      'units': 'percent'
    }, {
      'name': 'avg_stance_time_balance',
      'number': 133,
      'type': 'uint16',
      'scale': 100,
      'offset': 0,
      'units': 'percent'
    }, {
      'name': 'avg_step_length',
      'number': 134,
      'type': 'uint16',
      'scale': 10,
      'offset': 0,
      'units': 'mm'
    }, {
      'name': 'total_anaerobic_effect',
      'number': 137,
      'type': 'uint8',
      'scale': 10,
      'offset': 0,
      'units': ''
    }, {
      'name': 'avg_vam',
      'number': 139,
      'type': 'uint16',
      'scale': 1000,
      'offset': 0,
      'units': 'm/s'
    }, {
      'name': 'timestamp',
      'number': 253,
      'type': 'date_time',
      'scale': null,
      'offset': 0,
      'units': 's'
    }, { 'name': 'message_index', 'number': 254, 'type': 'message_index', 'scale': null, 'offset': 0, 'units': '' }]
  },
  'lap': {
    'num': 19,
    'fields': [{
      'name': 'event',
      'number': 0,
      'type': 'event',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'event_type',
      'number': 1,
      'type': 'event_type',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'start_time',
      'number': 2,
      'type': 'date_time',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'start_position_lat',
      'number': 3,
      'type': 'sint32',
      'scale': null,
      'offset': 0,
      'units': 'semicircles'
    }, {
      'name': 'start_position_long',
      'number': 4,
      'type': 'sint32',
      'scale': null,
      'offset': 0,
      'units': 'semicircles'
    }, {
      'name': 'end_position_lat',
      'number': 5,
      'type': 'sint32',
      'scale': null,
      'offset': 0,
      'units': 'semicircles'
    }, {
      'name': 'end_position_long',
      'number': 6,
      'type': 'sint32',
      'scale': null,
      'offset': 0,
      'units': 'semicircles'
    }, {
      'name': 'total_elapsed_time',
      'number': 7,
      'type': 'uint32',
      'scale': 1000,
      'offset': 0,
      'units': 's'
    }, {
      'name': 'total_timer_time',
      'number': 8,
      'type': 'uint32',
      'scale': 1000,
      'offset': 0,
      'units': 's'
    }, {
      'name': 'total_distance',
      'number': 9,
      'type': 'uint32',
      'scale': 100,
      'offset': 0,
      'units': 'm'
    }, {
      'name': 'total_cycles',
      'number': 10,
      'type': 'uint32',
      'scale': null,
      'offset': 0,
      'units': 'cycles'
    }, {
      'name': 'total_calories',
      'number': 11,
      'type': 'uint16',
      'scale': null,
      'offset': 0,
      'units': 'kcal'
    }, {
      'name': 'total_fat_calories',
      'number': 12,
      'type': 'uint16',
      'scale': null,
      'offset': 0,
      'units': 'kcal'
    }, {
      'name': 'avg_speed',
      'number': 13,
      'type': 'uint16',
      'scale': 1000,
      'offset': 0,
      'units': 'm/s'
    }, {
      'name': 'max_speed',
      'number': 14,
      'type': 'uint16',
      'scale': 1000,
      'offset': 0,
      'units': 'm/s'
    }, {
      'name': 'avg_heart_rate',
      'number': 15,
      'type': 'uint8',
      'scale': null,
      'offset': 0,
      'units': 'bpm'
    }, {
      'name': 'max_heart_rate',
      'number': 16,
      'type': 'uint8',
      'scale': null,
      'offset': 0,
      'units': 'bpm'
    }, {
      'name': 'avg_cadence',
      'number': 17,
      'type': 'uint8',
      'scale': null,
      'offset': 0,
      'units': 'rpm'
    }, {
      'name': 'max_cadence',
      'number': 18,
      'type': 'uint8',
      'scale': null,
      'offset': 0,
      'units': 'rpm'
    }, {
      'name': 'avg_power',
      'number': 19,
      'type': 'uint16',
      'scale': null,
      'offset': 0,
      'units': 'watts'
    }, {
      'name': 'max_power',
      'number': 20,
      'type': 'uint16',
      'scale': null,
      'offset': 0,
      'units': 'watts'
    }, {
      'name': 'total_ascent',
      'number': 21,
      'type': 'uint16',
      'scale': null,
      'offset': 0,
      'units': 'm'
    }, {
      'name': 'total_descent',
      'number': 22,
      'type': 'uint16',
      'scale': null,
      'offset': 0,
      'units': 'm'
    }, {
      'name': 'intensity',
      'number': 23,
      'type': 'intensity',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'lap_trigger',
      'number': 24,
      'type': 'lap_trigger',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'sport',
      'number': 25,
      'type': 'sport',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'event_group',
      'number': 26,
      'type': 'uint8',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'num_lengths',
      'number': 32,
      'type': 'uint16',
      'scale': null,
      'offset': 0,
      'units': 'lengths'
    }, {
      'name': 'normalized_power',
      'number': 33,
      'type': 'uint16',
      'scale': null,
      'offset': 0,
      'units': 'watts'
    }, {
      'name': 'left_right_balance',
      'number': 34,
      'type': 'left_right_balance_100',
      'scale': 100,
      'offset': 0,
      'units': '%'
    }, {
      'name': 'first_length_index',
      'number': 35,
      'type': 'uint16',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'avg_stroke_distance',
      'number': 37,
      'type': 'uint16',
      'scale': 100,
      'offset': 0,
      'units': 'm'
    }, {
      'name': 'swim_stroke',
      'number': 38,
      'type': 'swim_stroke',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'sub_sport',
      'number': 39,
      'type': 'sub_sport',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'num_active_lengths',
      'number': 40,
      'type': 'uint16',
      'scale': null,
      'offset': 0,
      'units': 'lengths'
    }, {
      'name': 'total_work',
      'number': 41,
      'type': 'uint32',
      'scale': null,
      'offset': 0,
      'units': 'J'
    }, {
      'name': 'avg_altitude',
      'number': 42,
      'type': 'uint16',
      'scale': 5,
      'offset': -500,
      'units': 'm'
    }, {
      'name': 'max_altitude',
      'number': 43,
      'type': 'uint16',
      'scale': 5,
      'offset': -500,
      'units': 'm'
    }, {
      'name': 'gps_accuracy',
      'number': 44,
      'type': 'uint8',
      'scale': null,
      'offset': 0,
      'units': 'm'
    }, {
      'name': 'avg_grade',
      'number': 45,
      'type': 'sint16',
      'scale': 100,
      'offset': 0,
      'units': '%'
    }, {
      'name': 'avg_pos_grade',
      'number': 46,
      'type': 'sint16',
      'scale': 100,
      'offset': 0,
      'units': '%'
    }, {
      'name': 'avg_neg_grade',
      'number': 47,
      'type': 'sint16',
      'scale': 100,
      'offset': 0,
      'units': '%'
    }, {
      'name': 'max_pos_grade',
      'number': 48,
      'type': 'sint16',
      'scale': 100,
      'offset': 0,
      'units': '%'
    }, {
      'name': 'max_neg_grade',
      'number': 49,
      'type': 'sint16',
      'scale': 100,
      'offset': 0,
      'units': '%'
    }, {
      'name': 'avg_temperature',
      'number': 50,
      'type': 'sint8',
      'scale': null,
      'offset': 0,
      'units': 'C'
    }, {
      'name': 'max_temperature',
      'number': 51,
      'type': 'sint8',
      'scale': null,
      'offset': 0,
      'units': 'C'
    }, {
      'name': 'total_moving_time',
      'number': 52,
      'type': 'uint32',
      'scale': 1000,
      'offset': 0,
      'units': 's'
    }, {
      'name': 'avg_pos_vertical_speed',
      'number': 53,
      'type': 'uint16',
      'scale': 1000,
      'offset': 0,
      'units': 'm/s'
    }, {
      'name': 'avg_neg_vertical_speed',
      'number': 54,
      'type': 'uint16',
      'scale': 1000,
      'offset': 0,
      'units': 'm/s'
    }, {
      'name': 'max_pos_vertical_speed',
      'number': 55,
      'type': 'uint16',
      'scale': 1000,
      'offset': 0,
      'units': 'm/s'
    }, {
      'name': 'max_neg_vertical_speed',
      'number': 56,
      'type': 'uint16',
      'scale': 1000,
      'offset': 0,
      'units': 'm/s'
    }, {
      'name': 'time_in_hr_zone',
      'number': 57,
      'type': 'uint32_array',
      'scale': 1000,
      'offset': 0,
      'units': 's'
    }, {
      'name': 'time_in_speed_zone',
      'number': 58,
      'type': 'uint32_array',
      'scale': 1000,
      'offset': 0,
      'units': 's'
    }, {
      'name': 'time_in_cadence_zone',
      'number': 59,
      'type': 'uint32_array',
      'scale': 1000,
      'offset': 0,
      'units': 's'
    }, {
      'name': 'time_in_power_zone',
      'number': 60,
      'type': 'uint32_array',
      'scale': 1000,
      'offset': 0,
      'units': 's'
    }, {
      'name': 'repetition_num',
      'number': 61,
      'type': 'uint16',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'min_altitude',
      'number': 62,
      'type': 'uint16',
      'scale': 5,
      'offset': -500,
      'units': 'm'
    }, {
      'name': 'min_heart_rate',
      'number': 63,
      'type': 'uint8',
      'scale': null,
      'offset': 0,
      'units': 'bpm'
    }, {
      'name': 'wkt_step_index',
      'number': 71,
      'type': 'message_index',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'opponent_score',
      'number': 74,
      'type': 'uint16',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'stroke_count',
      'number': 75,
      'type': 'uint16',
      'scale': null,
      'offset': 0,
      'units': 'counts'
    }, {
      'name': 'zone_count',
      'number': 76,
      'type': 'uint16',
      'scale': null,
      'offset': 0,
      'units': 'counts'
    }, {
      'name': 'avg_vertical_oscillation',
      'number': 77,
      'type': 'uint16',
      'scale': 10,
      'offset': 0,
      'units': 'mm'
    }, {
      'name': 'avg_stance_time_percent',
      'number': 78,
      'type': 'uint16',
      'scale': 100,
      'offset': 0,
      'units': 'percent'
    }, {
      'name': 'avg_stance_time',
      'number': 79,
      'type': 'uint16',
      'scale': 10,
      'offset': 0,
      'units': 'ms'
    }, {
      'name': 'avg_fractional_cadence',
      'number': 80,
      'type': 'uint8',
      'scale': 128,
      'offset': 0,
      'units': 'rpm'
    }, {
      'name': 'max_fractional_cadence',
      'number': 81,
      'type': 'uint8',
      'scale': 128,
      'offset': 0,
      'units': 'rpm'
    }, {
      'name': 'total_fractional_cycles',
      'number': 82,
      'type': 'uint8',
      'scale': 128,
      'offset': 0,
      'units': 'cycles'
    }, {
      'name': 'player_score',
      'number': 83,
      'type': 'uint16',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'avg_total_hemoglobin_conc',
      'number': 84,
      'type': 'uint16',
      'scale': 100,
      'offset': 0,
      'units': 'g/dL'
    }, {
      'name': 'min_total_hemoglobin_conc',
      'number': 85,
      'type': 'uint16',
      'scale': 100,
      'offset': 0,
      'units': 'g/dL'
    }, {
      'name': 'max_total_hemoglobin_conc',
      'number': 86,
      'type': 'uint16',
      'scale': 100,
      'offset': 0,
      'units': 'g/dL'
    }, {
      'name': 'avg_saturated_hemoglobin_percent',
      'number': 87,
      'type': 'uint16',
      'scale': 10,
      'offset': 0,
      'units': '%'
    }, {
      'name': 'min_saturated_hemoglobin_percent',
      'number': 88,
      'type': 'uint16',
      'scale': 10,
      'offset': 0,
      'units': '%'
    }, {
      'name': 'max_saturated_hemoglobin_percent',
      'number': 89,
      'type': 'uint16',
      'scale': 10,
      'offset': 0,
      'units': '%'
    }, {
      'name': 'avg_left_torque_effectiveness',
      'number': 91,
      'type': 'uint8',
      'scale': 2,
      'offset': 0,
      'units': 'percent'
    }, {
      'name': 'avg_right_torque_effectiveness',
      'number': 92,
      'type': 'uint8',
      'scale': 2,
      'offset': 0,
      'units': 'percent'
    }, {
      'name': 'avg_left_pedal_smoothness',
      'number': 93,
      'type': 'uint8',
      'scale': 2,
      'offset': 0,
      'units': 'percent'
    }, {
      'name': 'avg_right_pedal_smoothness',
      'number': 94,
      'type': 'uint8',
      'scale': 2,
      'offset': 0,
      'units': 'percent'
    }, {
      'name': 'avg_combined_pedal_smoothness',
      'number': 95,
      'type': 'uint8',
      'scale': 2,
      'offset': 0,
      'units': 'percent'
    }, {
      'name': 'time_standing',
      'number': 98,
      'type': 'uint32',
      'scale': 1000,
      'offset': 0,
      'units': 's'
    }, {
      'name': 'stand_count',
      'number': 99,
      'type': 'uint16',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'avg_left_pco',
      'number': 100,
      'type': 'sint8',
      'scale': null,
      'offset': 0,
      'units': 'mm'
    }, {
      'name': 'avg_right_pco',
      'number': 101,
      'type': 'sint8',
      'scale': null,
      'offset': 0,
      'units': 'mm'
    }, {
      'name': 'avg_left_power_phase',
      'number': 102,
      'type': 'uint8',
      'scale': null,
      'offset': 0,
      'units': 'degrees'
    }, {
      'name': 'avg_left_power_phase_peak',
      'number': 103,
      'type': 'uint8',
      'scale': null,
      'offset': 0,
      'units': 'degrees'
    }, {
      'name': 'avg_right_power_phase',
      'number': 104,
      'type': 'uint8',
      'scale': null,
      'offset': 0,
      'units': 'degrees'
    }, {
      'name': 'avg_right_power_phase_peak',
      'number': 105,
      'type': 'uint8',
      'scale': null,
      'offset': 0,
      'units': 'degrees'
    }, {
      'name': 'avg_power_position',
      'number': 106,
      'type': 'uint16',
      'scale': null,
      'offset': 0,
      'units': 'watts'
    }, {
      'name': 'max_power_position',
      'number': 107,
      'type': 'uint16',
      'scale': null,
      'offset': 0,
      'units': 'watts'
    }, {
      'name': 'avg_cadence_position',
      'number': 108,
      'type': 'uint8',
      'scale': null,
      'offset': 0,
      'units': 'rpm'
    }, {
      'name': 'max_cadence_position',
      'number': 109,
      'type': 'uint8',
      'scale': null,
      'offset': 0,
      'units': 'rpm'
    }, {
      'name': 'enhanced_avg_speed',
      'number': 110,
      'type': 'uint32',
      'scale': 1000,
      'offset': 0,
      'units': 'm/s'
    }, {
      'name': 'enhanced_max_speed',
      'number': 111,
      'type': 'uint32',
      'scale': 1000,
      'offset': 0,
      'units': 'm/s'
    }, {
      'name': 'enhanced_avg_altitude',
      'number': 112,
      'type': 'uint32',
      'scale': 5,
      'offset': -500,
      'units': 'm'
    }, {
      'name': 'enhanced_min_altitude',
      'number': 113,
      'type': 'uint32',
      'scale': 5,
      'offset': -500,
      'units': 'm'
    }, {
      'name': 'enhanced_max_altitude',
      'number': 114,
      'type': 'uint32',
      'scale': 5,
      'offset': -500,
      'units': 'm'
    }, {
      'name': 'avg_lev_motor_power',
      'number': 115,
      'type': 'uint16',
      'scale': null,
      'offset': 0,
      'units': 'watts'
    }, {
      'name': 'max_lev_motor_power',
      'number': 116,
      'type': 'uint16',
      'scale': null,
      'offset': 0,
      'units': 'watts'
    }, {
      'name': 'lev_battery_consumption',
      'number': 117,
      'type': 'uint8',
      'scale': 2,
      'offset': 0,
      'units': 'percent'
    }, {
      'name': 'avg_vertical_ratio',
      'number': 118,
      'type': 'uint16',
      'scale': 100,
      'offset': 0,
      'units': 'percent'
    }, {
      'name': 'avg_stance_time_balance',
      'number': 119,
      'type': 'uint16',
      'scale': 100,
      'offset': 0,
      'units': 'percent'
    }, {
      'name': 'avg_step_length',
      'number': 120,
      'type': 'uint16',
      'scale': 10,
      'offset': 0,
      'units': 'mm'
    }, {
      'name': 'avg_vam',
      'number': 121,
      'type': 'uint16',
      'scale': 1000,
      'offset': 0,
      'units': 'm/s'
    }, {
      'name': 'timestamp',
      'number': 253,
      'type': 'date_time',
      'scale': null,
      'offset': 0,
      'units': 's'
    }, { 'name': 'message_index', 'number': 254, 'type': 'message_index', 'scale': null, 'offset': 0, 'units': '' }]
  },
  'record': {
    'num': 20,
    'fields': [{
      'name': 'position_lat',
      'number': 0,
      'type': 'sint32',
      'scale': null,
      'offset': 0,
      'units': 'semicircles'
    }, {
      'name': 'position_long',
      'number': 1,
      'type': 'sint32',
      'scale': null,
      'offset': 0,
      'units': 'semicircles'
    }, {
      'name': 'altitude',
      'number': 2,
      'type': 'uint16',
      'scale': 5,
      'offset': -500,
      'units': 'm'
    }, {
      'name': 'heart_rate',
      'number': 3,
      'type': 'uint8',
      'scale': null,
      'offset': 0,
      'units': 'bpm'
    }, {
      'name': 'cadence',
      'number': 4,
      'type': 'uint8',
      'scale': null,
      'offset': 0,
      'units': 'rpm'
    }, {
      'name': 'distance',
      'number': 5,
      'type': 'uint32',
      'scale': 100,
      'offset': 0,
      'units': 'm'
    }, {
      'name': 'speed',
      'number': 6,
      'type': 'uint16',
      'scale': 1000,
      'offset': 0,
      'units': 'm/s'
    }, {
      'name': 'power',
      'number': 7,
      'type': 'uint16',
      'scale': null,
      'offset': 0,
      'units': 'watts'
    }, {
      'name': 'compressed_speed_distance',
      'number': 8,
      'type': 'byte',
      'scale': 100,
      'offset': 0,
      'units': 'm/s,m'
    }, {
      'name': 'grade',
      'number': 9,
      'type': 'sint16',
      'scale': 100,
      'offset': 0,
      'units': '%'
    }, {
      'name': 'resistance',
      'number': 10,
      'type': 'uint8',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'time_from_course',
      'number': 11,
      'type': 'sint32',
      'scale': 1000,
      'offset': 0,
      'units': 's'
    }, {
      'name': 'cycle_length',
      'number': 12,
      'type': 'uint8',
      'scale': 100,
      'offset': 0,
      'units': 'm'
    }, {
      'name': 'temperature',
      'number': 13,
      'type': 'sint8',
      'scale': null,
      'offset': 0,
      'units': 'C'
    }, {
      'name': 'speed_1s',
      'number': 17,
      'type': 'uint8',
      'scale': 16,
      'offset': 0,
      'units': 'm/s'
    }, {
      'name': 'cycles',
      'number': 18,
      'type': 'uint8',
      'scale': null,
      'offset': 0,
      'units': 'cycles'
    }, {
      'name': 'total_cycles',
      'number': 19,
      'type': 'uint32',
      'scale': null,
      'offset': 0,
      'units': 'cycles'
    }, {
      'name': 'compressed_accumulated_power',
      'number': 28,
      'type': 'uint16',
      'scale': null,
      'offset': 0,
      'units': 'watts'
    }, {
      'name': 'accumulated_power',
      'number': 29,
      'type': 'uint32',
      'scale': null,
      'offset': 0,
      'units': 'watts'
    }, {
      'name': 'left_right_balance',
      'number': 30,
      'type': 'left_right_balance',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'gps_accuracy',
      'number': 31,
      'type': 'uint8',
      'scale': null,
      'offset': 0,
      'units': 'm'
    }, {
      'name': 'vertical_speed',
      'number': 32,
      'type': 'sint16',
      'scale': 1000,
      'offset': 0,
      'units': 'm/s'
    }, {
      'name': 'calories',
      'number': 33,
      'type': 'uint16',
      'scale': null,
      'offset': 0,
      'units': 'kcal'
    }, {
      'name': 'vertical_oscillation',
      'number': 39,
      'type': 'uint16',
      'scale': 10,
      'offset': 0,
      'units': 'mm'
    }, {
      'name': 'stance_time_percent',
      'number': 40,
      'type': 'uint16',
      'scale': 100,
      'offset': 0,
      'units': 'percent'
    }, {
      'name': 'stance_time',
      'number': 41,
      'type': 'uint16',
      'scale': 10,
      'offset': 0,
      'units': 'ms'
    }, {
      'name': 'activity_type',
      'number': 42,
      'type': 'activity_type',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'left_torque_effectiveness',
      'number': 43,
      'type': 'uint8',
      'scale': 2,
      'offset': 0,
      'units': 'percent'
    }, {
      'name': 'right_torque_effectiveness',
      'number': 44,
      'type': 'uint8',
      'scale': 2,
      'offset': 0,
      'units': 'percent'
    }, {
      'name': 'left_pedal_smoothness',
      'number': 45,
      'type': 'uint8',
      'scale': 2,
      'offset': 0,
      'units': 'percent'
    }, {
      'name': 'right_pedal_smoothness',
      'number': 46,
      'type': 'uint8',
      'scale': 2,
      'offset': 0,
      'units': 'percent'
    }, {
      'name': 'combined_pedal_smoothness',
      'number': 47,
      'type': 'uint8',
      'scale': 2,
      'offset': 0,
      'units': 'percent'
    }, {
      'name': 'time128',
      'number': 48,
      'type': 'uint8',
      'scale': 128,
      'offset': 0,
      'units': 's'
    }, {
      'name': 'stroke_type',
      'number': 49,
      'type': 'stroke_type',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'zone',
      'number': 50,
      'type': 'uint8',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'ball_speed',
      'number': 51,
      'type': 'uint16',
      'scale': 100,
      'offset': 0,
      'units': 'm/s'
    }, {
      'name': 'cadence256',
      'number': 52,
      'type': 'uint16',
      'scale': 256,
      'offset': 0,
      'units': 'rpm'
    }, {
      'name': 'fractional_cadence',
      'number': 53,
      'type': 'uint8',
      'scale': 128,
      'offset': 0,
      'units': 'rpm'
    }, {
      'name': 'total_hemoglobin_conc',
      'number': 54,
      'type': 'uint16',
      'scale': 100,
      'offset': 0,
      'units': 'g/dL'
    }, {
      'name': 'total_hemoglobin_conc_min',
      'number': 55,
      'type': 'uint16',
      'scale': 100,
      'offset': 0,
      'units': 'g/dL'
    }, {
      'name': 'total_hemoglobin_conc_max',
      'number': 56,
      'type': 'uint16',
      'scale': 100,
      'offset': 0,
      'units': 'g/dL'
    }, {
      'name': 'saturated_hemoglobin_percent',
      'number': 57,
      'type': 'uint16',
      'scale': 10,
      'offset': 0,
      'units': '%'
    }, {
      'name': 'saturated_hemoglobin_percent_min',
      'number': 58,
      'type': 'uint16',
      'scale': 10,
      'offset': 0,
      'units': '%'
    }, {
      'name': 'saturated_hemoglobin_percent_max',
      'number': 59,
      'type': 'uint16',
      'scale': 10,
      'offset': 0,
      'units': '%'
    }, {
      'name': 'device_index',
      'number': 62,
      'type': 'device_index',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'left_pco',
      'number': 67,
      'type': 'sint8',
      'scale': null,
      'offset': 0,
      'units': 'mm'
    }, {
      'name': 'right_pco',
      'number': 68,
      'type': 'sint8',
      'scale': null,
      'offset': 0,
      'units': 'mm'
    }, {
      'name': 'left_power_phase',
      'number': 69,
      'type': 'uint8',
      'scale': null,
      'offset': 0,
      'units': 'degrees'
    }, {
      'name': 'left_power_phase_peak',
      'number': 70,
      'type': 'uint8',
      'scale': null,
      'offset': 0,
      'units': 'degrees'
    }, {
      'name': 'right_power_phase',
      'number': 71,
      'type': 'uint8',
      'scale': null,
      'offset': 0,
      'units': 'degrees'
    }, {
      'name': 'right_power_phase_peak',
      'number': 72,
      'type': 'uint8',
      'scale': null,
      'offset': 0,
      'units': 'degrees'
    }, {
      'name': 'enhanced_speed',
      'number': 73,
      'type': 'uint32',
      'scale': 1000,
      'offset': 0,
      'units': 'm/s'
    }, {
      'name': 'enhanced_altitude',
      'number': 78,
      'type': 'uint32',
      'scale': 5,
      'offset': -500,
      'units': 'm'
    }, {
      'name': 'battery_soc',
      'number': 81,
      'type': 'uint8',
      'scale': 2,
      'offset': 0,
      'units': 'percent'
    }, {
      'name': 'motor_power',
      'number': 82,
      'type': 'uint16',
      'scale': null,
      'offset': 0,
      'units': 'watts'
    }, {
      'name': 'vertical_ratio',
      'number': 83,
      'type': 'uint16',
      'scale': 100,
      'offset': 0,
      'units': 'percent'
    }, {
      'name': 'stance_time_balance',
      'number': 84,
      'type': 'uint16',
      'scale': 100,
      'offset': 0,
      'units': 'percent'
    }, {
      'name': 'step_length',
      'number': 85,
      'type': 'uint16',
      'scale': 10,
      'offset': 0,
      'units': 'mm'
    }, {
      'name': 'absolute_pressure',
      'number': 91,
      'type': 'uint32',
      'scale': null,
      'offset': 0,
      'units': 'Pa'
    }, {
      'name': 'depth',
      'number': 92,
      'type': 'uint32',
      'scale': null,
      'offset': 0,
      'units': 'm'
    }, {
      'name': 'next_stop_depth',
      'number': 93,
      'type': 'uint32',
      'scale': null,
      'offset': 0,
      'units': 'm'
    }, {
      'name': 'next_stop_time',
      'number': 94,
      'type': 'uint32',
      'scale': null,
      'offset': 0,
      'units': 's'
    }, {
      'name': 'time_to_surface',
      'number': 95,
      'type': 'uint32',
      'scale': null,
      'offset': 0,
      'units': 's'
    }, {
      'name': 'ndl_time',
      'number': 96,
      'type': 'uint32',
      'scale': null,
      'offset': 0,
      'units': 's'
    }, {
      'name': 'cns_load',
      'number': 97,
      'type': 'uint8',
      'scale': null,
      'offset': 0,
      'units': 'percent'
    }, {
      'name': 'n2_load',
      'number': 98,
      'type': 'uint16',
      'scale': null,
      'offset': 0,
      'units': 'percent'
    }, { 'name': 'timestamp', 'number': 253, 'type': 'date_time', 'scale': null, 'offset': 0, 'units': 's' }]
  },
  'event': {
    'num': 21,
    'fields': [{
      'name': 'event',
      'number': 0,
      'type': 'event',
      'scale': null,
      'offset': null,
      'units': ''
    }, {
      'name': 'event_type',
      'number': 1,
      'type': 'event_type',
      'scale': null,
      'offset': null,
      'units': ''
    }, { 'name': 'data16', 'number': 2, 'type': 'uint16', 'scale': null, 'offset': null, 'units': '' }, {
      'name': 'data',
      'number': 3,
      'type': 'uint32',
      'scale': null,
      'offset': null,
      'units': ''
    }, {
      'name': 'event_group',
      'number': 4,
      'type': 'uint8',
      'scale': null,
      'offset': null,
      'units': ''
    }, {
      'name': 'score',
      'number': 7,
      'type': 'uint16',
      'scale': null,
      'offset': null,
      'units': ''
    }, {
      'name': 'opponent_score',
      'number': 8,
      'type': 'uint16',
      'scale': null,
      'offset': null,
      'units': ''
    }, {
      'name': 'front_gear_num',
      'number': 9,
      'type': 'uint8z',
      'scale': null,
      'offset': null,
      'units': ''
    }, {
      'name': 'front_gear',
      'number': 10,
      'type': 'uint8z',
      'scale': null,
      'offset': null,
      'units': ''
    }, {
      'name': 'rear_gear_num',
      'number': 11,
      'type': 'uint8z',
      'scale': null,
      'offset': null,
      'units': ''
    }, {
      'name': 'rear_gear',
      'number': 12,
      'type': 'uint8z',
      'scale': null,
      'offset': null,
      'units': ''
    }, {
      'name': 'device_index',
      'number': 13,
      'type': 'device_index',
      'scale': null,
      'offset': null,
      'units': ''
    }, { 'name': 'timestamp', 'number': 253, 'type': 'date_time', 'scale': null, 'offset': null, 'units': 's' }]
  },
  'device_info': {
    'num': 23,
    'fields': [{
      'name': 'device_index',
      'number': 0,
      'type': 'uint8',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'device_type',
      'number': 1,
      'type': 'antplus_device_type',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'manufacturer',
      'number': 2,
      'type': 'manufacturer',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'serial_number',
      'number': 3,
      'type': 'uint32z',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'product',
      'number': 4,
      'type': 'uint16',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'software_version',
      'number': 5,
      'type': 'uint16',
      'scale': 100,
      'offset': 0,
      'units': ''
    }, {
      'name': 'hardware_version',
      'number': 6,
      'type': 'uint8',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'cum_operating_time',
      'number': 7,
      'type': 'uint32',
      'scale': null,
      'offset': 0,
      'units': 's'
    }, {
      'name': 'battery_voltage',
      'number': 10,
      'type': 'uint16',
      'scale': 256,
      'offset': 0,
      'units': 'V'
    }, {
      'name': 'battery_status',
      'number': 11,
      'type': 'battery_status',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'sensor_position',
      'number': 18,
      'type': 'body_location',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'descriptor',
      'number': 19,
      'type': 'string',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'ant_transmission_type',
      'number': 20,
      'type': 'uint8z',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'ant_device_number',
      'number': 21,
      'type': 'uint16z',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'ant_network',
      'number': 22,
      'type': 'ant_network',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'source_type',
      'number': 25,
      'type': 'source_type',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'product_name',
      'number': 27,
      'type': 'string',
      'scale': null,
      'offset': 0,
      'units': ''
    }, { 'name': 'timestamp', 'number': 253, 'type': 'date_time', 'scale': null, 'offset': 0, 'units': 's' }]
  },
  'workout': {
    'num': 26,
    'fields': [{
      'name': 'sport',
      'number': 4,
      'type': 'sport',
      'scale': null,
      'offset': null,
      'units': ''
    }, {
      'name': 'capabilities',
      'number': 5,
      'type': 'workout_capabilities',
      'scale': null,
      'offset': null,
      'units': ''
    }, {
      'name': 'num_valid_steps',
      'number': 6,
      'type': 'uint16',
      'scale': null,
      'offset': null,
      'units': ''
    }, { 'name': 'wkt_name', 'number': 8, 'type': 'string', 'scale': null, 'offset': null, 'units': '' }]
  },
  'workout_step': {
    'num': 27,
    'fields': [{
      'name': 'wkt_step_name',
      'number': 0,
      'type': 'string',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'duration_type',
      'number': 1,
      'type': 'wkt_step_duration',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'duration_value',
      'number': 2,
      'type': 'uint32',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'target_type',
      'number': 3,
      'type': 'wkt_step_target',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'target_value',
      'number': 4,
      'type': 'uint32',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'custom_target_value_low',
      'number': 5,
      'type': 'uint32',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'custom_target_value_high',
      'number': 6,
      'type': 'uint32',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'intensity',
      'number': 7,
      'type': 'intensity',
      'scale': null,
      'offset': 0,
      'units': ''
    }, { 'name': 'message_index', 'number': 254, 'type': 'message_index', 'scale': null, 'offset': 0, 'units': '' }]
  },
  'weight_scale': {
    'num': 30,
    'fields': [{
      'name': 'weight',
      'number': 0,
      'type': 'weight',
      'scale': 100,
      'offset': 0,
      'units': 'kg'
    }, {
      'name': 'percent_fat',
      'number': 1,
      'type': 'uint16',
      'scale': 100,
      'offset': 0,
      'units': '%'
    }, {
      'name': 'percent_hydration',
      'number': 2,
      'type': 'uint16',
      'scale': 100,
      'offset': 0,
      'units': '%'
    }, {
      'name': 'visceral_fat_mass',
      'number': 3,
      'type': 'uint16',
      'scale': 100,
      'offset': 0,
      'units': 'kg'
    }, {
      'name': 'bone_mass',
      'number': 4,
      'type': 'uint16',
      'scale': 100,
      'offset': 0,
      'units': 'kg'
    }, {
      'name': 'muscle_mass',
      'number': 5,
      'type': 'uint16',
      'scale': 100,
      'offset': 0,
      'units': 'kg'
    }, {
      'name': 'basal_met',
      'number': 7,
      'type': 'uint16',
      'scale': 4,
      'offset': 0,
      'units': 'kcal/day'
    }, {
      'name': 'physique_rating',
      'number': 8,
      'type': 'uint8',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'active_met',
      'number': 9,
      'type': 'uint16',
      'scale': 4,
      'offset': 0,
      'units': 'kcal/day'
    }, {
      'name': 'metabolic_age',
      'number': 10,
      'type': 'uint8',
      'scale': null,
      'offset': 0,
      'units': 'years'
    }, {
      'name': 'visceral_fat_rating',
      'number': 11,
      'type': 'uint8',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'user_profile_index',
      'number': 12,
      'type': 'message_index',
      'scale': null,
      'offset': 0,
      'units': ''
    }, { 'name': 'timestamp', 'number': 253, 'type': 'date_time', 'scale': null, 'offset': 0, 'units': 's' }]
  },
  'course': {
    'num': 31,
    'fields': [{
      'name': 'sport',
      'number': 4,
      'type': 'sport',
      'scale': null,
      'offset': null,
      'units': ''
    }, {
      'name': 'name',
      'number': 5,
      'type': 'string',
      'scale': null,
      'offset': null,
      'units': ''
    }, { 'name': 'capabilities', 'number': 6, 'type': 'course_capabilities', 'scale': null, 'offset': null, 'units': '' }]
  },
  'course_point': {
    'num': 32,
    'fields': [{
      'name': 'timestamp',
      'number': 1,
      'type': 'date_time',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'position_lat',
      'number': 2,
      'type': 'sint32',
      'scale': null,
      'offset': 0,
      'units': 'semicircles'
    }, {
      'name': 'position_long',
      'number': 3,
      'type': 'sint32',
      'scale': null,
      'offset': 0,
      'units': 'semicircles'
    }, { 'name': 'distance', 'number': 4, 'type': 'uint32', 'scale': 100, 'offset': 0, 'units': 'm' }, {
      'name': 'type',
      'number': 5,
      'type': 'course_point',
      'scale': null,
      'offset': 0,
      'units': ''
    }, { 'name': 'name', 'number': 6, 'type': 'string', 'scale': null, 'offset': 0, 'units': '' }, {
      'name': 'favorite',
      'number': 8,
      'type': 'bool',
      'scale': null,
      'offset': 0,
      'units': ''
    }, { 'name': 'message_index', 'number': 254, 'type': 'message_index', 'scale': null, 'offset': 0, 'units': '' }]
  },
  'totals': {
    'num': 33,
    'fields': [{
      'name': 'timer_time',
      'number': 0,
      'type': 'uint32',
      'scale': null,
      'offset': 0,
      'units': 's'
    }, {
      'name': 'distance',
      'number': 1,
      'type': 'uint32',
      'scale': null,
      'offset': 0,
      'units': 'm'
    }, {
      'name': 'calories',
      'number': 2,
      'type': 'uint32',
      'scale': null,
      'offset': 0,
      'units': 'kcal'
    }, {
      'name': 'sport',
      'number': 3,
      'type': 'sport',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'elapsed_time',
      'number': 4,
      'type': 'uint32',
      'scale': null,
      'offset': 0,
      'units': 's'
    }, {
      'name': 'sessions',
      'number': 5,
      'type': 'uint16',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'active_time',
      'number': 6,
      'type': 'uint32',
      'scale': null,
      'offset': 0,
      'units': 's'
    }, {
      'name': 'sport_index',
      'number': 9,
      'type': 'uint8',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'timestamp',
      'number': 253,
      'type': 'date_time',
      'scale': null,
      'offset': 0,
      'units': 's'
    }, { 'name': 'message_index', 'number': 254, 'type': 'message_index', 'scale': null, 'offset': 0, 'units': '' }]
  },
  'activity': {
    'num': 34,
    'fields': [{
      'name': 'total_timer_time',
      'number': 0,
      'type': 'uint32',
      'scale': 1000,
      'offset': 0,
      'units': 's'
    }, {
      'name': 'num_sessions',
      'number': 1,
      'type': 'uint16',
      'scale': null,
      'offset': 0,
      'units': ''
    }, { 'name': 'type', 'number': 2, 'type': 'activity', 'scale': null, 'offset': 0, 'units': '' }, {
      'name': 'event',
      'number': 3,
      'type': 'event',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'event_type',
      'number': 4,
      'type': 'event_type',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'local_timestamp',
      'number': 5,
      'type': 'local_date_time',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'event_group',
      'number': 6,
      'type': 'uint8',
      'scale': null,
      'offset': 0,
      'units': ''
    }, { 'name': 'timestamp', 'number': 253, 'type': 'date_time', 'scale': null, 'offset': 0, 'units': '' }]
  },
  'software': {
    'num': 35,
    'fields': [{
      'name': 'version',
      'number': 3,
      'type': 'uint16',
      'scale': 100,
      'offset': null,
      'units': ''
    }, {
      'name': 'part_number',
      'number': 5,
      'type': 'string',
      'scale': null,
      'offset': null,
      'units': ''
    }, { 'name': 'message_index', 'number': 254, 'type': 'message_index', 'scale': null, 'offset': null, 'units': '' }]
  },
  'file_capabilities': {
    'num': 37,
    'fields': [{
      'name': 'type',
      'number': 0,
      'type': 'file',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'flags',
      'number': 1,
      'type': 'file_flags',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'directory',
      'number': 2,
      'type': 'string',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'max_count',
      'number': 3,
      'type': 'uint16',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'max_size',
      'number': 4,
      'type': 'uint32',
      'scale': null,
      'offset': 0,
      'units': 'bytes'
    }, { 'name': 'message_index', 'number': 254, 'type': 'message_index', 'scale': null, 'offset': 0, 'units': '' }]
  },
  'mesg_capabilities': {
    'num': 38,
    'fields': [{
      'name': 'file',
      'number': 0,
      'type': 'file',
      'scale': null,
      'offset': null,
      'units': ''
    }, {
      'name': 'mesg_num',
      'number': 1,
      'type': 'mesg_num',
      'scale': null,
      'offset': null,
      'units': ''
    }, {
      'name': 'count_type',
      'number': 2,
      'type': 'mesg_count',
      'scale': null,
      'offset': null,
      'units': ''
    }, {
      'name': 'count',
      'number': 3,
      'type': 'uint16',
      'scale': null,
      'offset': null,
      'units': ''
    }, { 'name': 'message_index', 'number': 254, 'type': 'message_index', 'scale': null, 'offset': null, 'units': '' }]
  },
  'field_capabilities': {
    'num': 39,
    'fields': [{
      'name': 'file',
      'number': 0,
      'type': 'file',
      'scale': null,
      'offset': null,
      'units': ''
    }, {
      'name': 'mesg_num',
      'number': 1,
      'type': 'mesg_num',
      'scale': null,
      'offset': null,
      'units': ''
    }, {
      'name': 'field_num',
      'number': 2,
      'type': 'uint8',
      'scale': null,
      'offset': null,
      'units': ''
    }, {
      'name': 'count',
      'number': 3,
      'type': 'uint16',
      'scale': null,
      'offset': null,
      'units': ''
    }, { 'name': 'message_index', 'number': 254, 'type': 'message_index', 'scale': null, 'offset': null, 'units': '' }]
  },
  'file_creator': {
    'num': 49,
    'fields': [{
      'name': 'software_version',
      'number': 0,
      'type': 'uint16',
      'scale': null,
      'offset': null,
      'units': ''
    }, { 'name': 'hardware_version', 'number': 1, 'type': 'uint8', 'scale': null, 'offset': null, 'units': '' }]
  },
  'blood_pressure': {
    'num': 51,
    'fields': [{
      'name': 'systolic_pressure',
      'number': 0,
      'type': 'uint16',
      'scale': null,
      'offset': 0,
      'units': 'mmHg'
    }, {
      'name': 'diastolic_pressure',
      'number': 1,
      'type': 'uint16',
      'scale': null,
      'offset': 0,
      'units': 'mmHg'
    }, {
      'name': 'mean_arterial_pressure',
      'number': 2,
      'type': 'uint16',
      'scale': null,
      'offset': 0,
      'units': 'mmHg'
    }, {
      'name': 'map_3_sample_mean',
      'number': 3,
      'type': 'uint16',
      'scale': null,
      'offset': 0,
      'units': 'mmHg'
    }, {
      'name': 'map_morning_values',
      'number': 4,
      'type': 'uint16',
      'scale': null,
      'offset': 0,
      'units': 'mmHg'
    }, {
      'name': 'map_evening_values',
      'number': 5,
      'type': 'uint16',
      'scale': null,
      'offset': 0,
      'units': 'mmHg'
    }, {
      'name': 'heart_rate',
      'number': 6,
      'type': 'uint8',
      'scale': null,
      'offset': 0,
      'units': 'bpm'
    }, {
      'name': 'heart_rate_type',
      'number': 7,
      'type': 'hr_type',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'status',
      'number': 8,
      'type': 'bp_status',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'user_profile_index',
      'number': 9,
      'type': 'message_index',
      'scale': null,
      'offset': 0,
      'units': ''
    }, { 'name': 'timestamp', 'number': 253, 'type': 'date_time', 'scale': null, 'offset': 0, 'units': 's' }]
  },
  'monitoring': {
    'num': 55,
    'fields': [{
      'name': 'device_index',
      'number': 0,
      'type': 'device_index',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'calories',
      'number': 1,
      'type': 'uint16',
      'scale': null,
      'offset': 0,
      'units': 'kcal'
    }, {
      'name': 'distance',
      'number': 2,
      'type': 'float32',
      'scale': null,
      'offset': 0,
      'units': 'm'
    }, {
      'name': 'cycles',
      'number': 3,
      'type': 'float32',
      'scale': null,
      'offset': 0,
      'units': 'cycles'
    }, {
      'name': 'active_time',
      'number': 4,
      'type': 'float32',
      'scale': null,
      'offset': 0,
      'units': 's'
    }, {
      'name': 'activity_type',
      'number': 5,
      'type': 'activity_type',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'activity_subtype',
      'number': 6,
      'type': 'activity_subtype',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'activity_level',
      'number': 7,
      'type': 'activity_level',
      'scale': null,
      'offset': 0,
      'units': 's'
    }, {
      'name': 'distance16',
      'number': 8,
      'type': 'uint16',
      'scale': null,
      'offset': 0,
      'units': 'm'
    }, {
      'name': 'cycles16',
      'number': 9,
      'type': 'uint16',
      'scale': null,
      'offset': 0,
      'units': 'cycles'
    }, {
      'name': 'active_time16',
      'number': 10,
      'type': 'uint16',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'local_timestamp',
      'number': 11,
      'type': 'uint32',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'temperature',
      'number': 12,
      'type': 'float32',
      'scale': null,
      'offset': 0,
      'units': 'C'
    }, {
      'name': 'temperature_min',
      'number': 14,
      'type': 'float32',
      'scale': null,
      'offset': 0,
      'units': 'C'
    }, {
      'name': 'temperature_max',
      'number': 15,
      'type': 'float32',
      'scale': null,
      'offset': 0,
      'units': 'C'
    }, {
      'name': 'activity_time',
      'number': 16,
      'type': 'int32',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'active_calories',
      'number': 19,
      'type': 'uint16',
      'scale': null,
      'offset': 0,
      'units': 'kcal'
    }, {
      'name': 'current_activity_type_intensity',
      'number': 24,
      'type': 'uint8',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'timestamp_min8',
      'number': 25,
      'type': 'uint8',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'timestamp16',
      'number': 26,
      'type': 'uint16',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'heart_rate',
      'number': 27,
      'type': 'uint8',
      'scale': null,
      'offset': 0,
      'units': 'bpm'
    }, {
      'name': 'intensity',
      'number': 28,
      'type': 'uint8',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'duration_min',
      'number': 29,
      'type': 'uint16',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'duration',
      'number': 30,
      'type': 'uint32',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'ascent',
      'number': 31,
      'type': 'float32',
      'scale': null,
      'offset': 0,
      'units': 'm'
    }, {
      'name': 'descent',
      'number': 32,
      'type': 'float32',
      'scale': null,
      'offset': 0,
      'units': 'm'
    }, {
      'name': 'moderate_activity_minutes',
      'number': 33,
      'type': 'uint16',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'vigorous_activity_inutes',
      'number': 34,
      'type': 'uint16',
      'scale': null,
      'offset': 0,
      'units': ''
    }, { 'name': 'timestamp', 'number': 253, 'type': 'uint32', 'scale': null, 'offset': 0, 'units': '' }]
  },
  'hrv': {
    'num': 78,
    'fields': [{ 'name': 'time', 'number': 0, 'type': 'uint16_array', 'scale': 1000, 'offset': 0, 'units': 's' }]
  },
  'length': {
    'num': 101,
    'fields': [{
      'name': 'event',
      'number': 0,
      'type': 'event',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'event_type',
      'number': 1,
      'type': 'event_type',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'start_time',
      'number': 2,
      'type': 'date_time',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'total_elapsed_time',
      'number': 3,
      'type': 'uint32',
      'scale': 1000,
      'offset': 0,
      'units': 's'
    }, {
      'name': 'total_timer_time',
      'number': 4,
      'type': 'uint32',
      'scale': 1000,
      'offset': 0,
      'units': 's'
    }, {
      'name': 'total_strokes',
      'number': 5,
      'type': 'uint16',
      'scale': null,
      'offset': 0,
      'units': 'strokes'
    }, {
      'name': 'avg_speed',
      'number': 6,
      'type': 'uint16',
      'scale': 1000,
      'offset': 0,
      'units': 'm/s'
    }, {
      'name': 'swim_stroke',
      'number': 7,
      'type': 'swim_stroke',
      'scale': null,
      'offset': 0,
      'units': 'swim_stroke'
    }, {
      'name': 'avg_swimming_cadence',
      'number': 9,
      'type': 'uint8',
      'scale': null,
      'offset': 0,
      'units': 'strokes/min'
    }, {
      'name': 'event_group',
      'number': 10,
      'type': 'uint8',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'total_calories',
      'number': 11,
      'type': 'uint16',
      'scale': null,
      'offset': 0,
      'units': 'kcal'
    }, {
      'name': 'length_type',
      'number': 12,
      'type': 'length_type',
      'scale': null,
      'offset': 0,
      'units': 'length_type'
    }, {
      'name': 'player_score',
      'number': 18,
      'type': 'uint16',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'opponent_score',
      'number': 19,
      'type': 'uint16',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'stroke_count',
      'number': 20,
      'type': 'uint16',
      'scale': null,
      'offset': 0,
      'units': 'counts'
    }, {
      'name': 'zone_count',
      'number': 21,
      'type': 'uint16',
      'scale': null,
      'offset': 0,
      'units': 'counts'
    }, {
      'name': 'timestamp',
      'number': 253,
      'type': 'date_time',
      'scale': null,
      'offset': 0,
      'units': 's'
    }, { 'name': 'message_index', 'number': 254, 'type': 'message_index', 'scale': null, 'offset': 0, 'units': '' }]
  },
  'monitoring_info': {
    'num': 103,
    'fields': [{
      'name': 'local_timestamp',
      'number': 0,
      'type': 'uint32',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'activity_type',
      'number': 1,
      'type': 'activity_type',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'cycles_to_distance',
      'number': 3,
      'type': 'float32',
      'scale': null,
      'offset': 0,
      'units': 'cycles'
    }, {
      'name': 'cycles_to_calories',
      'number': 4,
      'type': 'float32',
      'scale': null,
      'offset': 0,
      'units': 'kcal'
    }, {
      'name': 'resting_metabolic_rate',
      'number': 5,
      'type': 'uint16',
      'scale': null,
      'offset': 0,
      'units': ''
    }, { 'name': 'timestamp', 'number': 253, 'type': 'date_time', 'scale': null, 'offset': 0, 'units': '' }]
  },
  'o_hr_settings': {
    'num': 108,
    'fields': [{
      'name': 'enabled',
      'number': 0,
      'type': 'byte',
      'scale': null,
      'offset': 0,
      'units': ''
    }, { 'name': 'timestamp', 'number': 253, 'type': 'date_time', 'scale': null, 'offset': 0, 'units': '' }]
  },
  'field_description': {
    'num': 206,
    'fields': [{
      'name': 'developer_data_index',
      'number': 0,
      'type': 'uint8',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'field_definition_number',
      'number': 1,
      'type': 'uint8',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'fit_base_type_id',
      'number': 2,
      'type': 'uint8',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'field_name',
      'number': 3,
      'type': 'string',
      'scale': null,
      'offset': 0,
      'units': ''
    }, { 'name': 'scale', 'number': 6, 'type': 'uint8', 'scale': null, 'offset': 0, 'units': '' }, {
      'name': 'offset',
      'number': 7,
      'type': 'sint8',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'units',
      'number': 8,
      'type': 'string',
      'scale': null,
      'offset': 0,
      'units': ''
    }, { 'name': 'native_field_num', 'number': 15, 'type': 'uint8', 'scale': null, 'offset': 0, 'units': '' }]
  },
  'developer_data_id': {
    'num': 207,
    'fields': [{
      'name': 'developer_id',
      'number': 0,
      'type': 'uint8',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'application_id',
      'number': 1,
      'type': 'byte_array',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'manufacturer_id',
      'number': 2,
      'type': 'manufacturer',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'developer_data_index',
      'number': 3,
      'type': 'uint8',
      'scale': null,
      'offset': 0,
      'units': ''
    }, { 'name': 'application_version', 'number': 4, 'type': 'uint8', 'scale': null, 'offset': 0, 'units': '' }]
  },
  'stress_level': {
    'num': 227,
    'fields': [{
      'name': 'stress_level_value',
      'number': 0,
      'type': 'uint16',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'stress_level_time',
      'number': 1,
      'type': 'date_time',
      'scale': null,
      'offset': 0,
      'units': 's'
    }, {
      'name': 'field_two',
      'number': 2,
      'type': 'sint8',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'body_battery',
      'number': 3,
      'type': 'uint8',
      'scale': null,
      'offset': 0,
      'units': ''
    }, { 'name': 'field_four', 'number': 4, 'type': 'uint8', 'scale': null, 'offset': 0, 'units': '' }]
  },
  'dive_settings': {
    'num': 258,
    'fields': [{
      'name': 'name',
      'number': 0,
      'type': 'string',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'model',
      'number': 1,
      'type': 'tissue_model_type',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'gf_low',
      'number': 2,
      'type': 'uint8',
      'scale': null,
      'offset': 0,
      'units': 'percent'
    }, {
      'name': 'gf_high',
      'number': 3,
      'type': 'uint8',
      'scale': null,
      'offset': 0,
      'units': 'percent'
    }, {
      'name': 'water_type',
      'number': 4,
      'type': 'water_type',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'water_density',
      'number': 5,
      'type': 'float32',
      'scale': null,
      'offset': 0,
      'units': 'kg/m^3'
    }, {
      'name': 'po2_warn',
      'number': 6,
      'type': 'uint8',
      'scale': null,
      'offset': 0,
      'units': 'percent'
    }, {
      'name': 'po2_critical',
      'number': 7,
      'type': 'uint8',
      'scale': null,
      'offset': 0,
      'units': 'percent'
    }, {
      'name': 'po2_deco',
      'number': 8,
      'type': 'uint8',
      'scale': null,
      'offset': 0,
      'units': 'percent'
    }, {
      'name': 'safety_stop_enabled',
      'number': 9,
      'type': 'bool',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'bottom_depth',
      'number': 10,
      'type': 'float32',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'bottom_time',
      'number': 11,
      'type': 'uint32',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'apnea_countdown_enabled',
      'number': 12,
      'type': 'bool',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'apnea_countdown_time',
      'number': 13,
      'type': 'uint32',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'backlight_mode',
      'number': 14,
      'type': 'dive_backlight_mode',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'backlight_brightness',
      'number': 15,
      'type': 'uint8',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'backlight_timeout',
      'number': 16,
      'type': 'backlight_timeout',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'repeat_dive_time',
      'number': 17,
      'type': 'uint16',
      'scale': null,
      'offset': 0,
      'units': 's'
    }, {
      'name': 'safety_stop_time',
      'number': 18,
      'type': 'uint16',
      'scale': null,
      'offset': 0,
      'units': 's'
    }, {
      'name': 'heart_rate_source_type',
      'number': 19,
      'type': 'source_type',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'heart_rate_source',
      'number': 20,
      'type': 'uint8',
      'scale': null,
      'offset': 0,
      'units': ''
    }, { 'name': 'message_index', 'number': 254, 'type': 'message_index', 'scale': null, 'offset': null, 'units': '' }]
  },
  'dive_gas': {
    'num': 259,
    'fields': [{
      'name': 'helium_content',
      'number': 0,
      'type': 'uint8',
      'scale': null,
      'offset': null,
      'units': 'percent'
    }, {
      'name': 'oxygen_content',
      'number': 1,
      'type': 'uint8',
      'scale': null,
      'offset': null,
      'units': 'percent'
    }, {
      'name': 'status',
      'number': 2,
      'type': 'dive_gas_status',
      'scale': null,
      'offset': null,
      'units': ''
    }, { 'name': 'message_index', 'number': 254, 'type': 'message_index', 'scale': null, 'offset': null, 'units': '' }]
  },
  'dive_alarm': {
    'num': 262,
    'fields': [{
      'name': 'depth',
      'number': 0,
      'type': 'uint32',
      'scale': null,
      'offset': null,
      'units': 'm'
    }, {
      'name': 'time',
      'number': 1,
      'type': 'sint32',
      'scale': null,
      'offset': null,
      'units': 's'
    }, {
      'name': 'enabled',
      'number': 2,
      'type': 'bool',
      'scale': null,
      'offset': null,
      'units': ''
    }, {
      'name': 'alarm_type',
      'number': 3,
      'type': 'dive_alarm_type',
      'scale': null,
      'offset': null,
      'units': ''
    }, {
      'name': 'sound',
      'number': 4,
      'type': 'tone',
      'scale': null,
      'offset': null,
      'units': ''
    }, {
      'name': 'dive_types',
      'number': 5,
      'type': 'sub_sport',
      'scale': null,
      'offset': null,
      'units': ''
    }, { 'name': 'message_index', 'number': 254, 'type': 'message_index', 'scale': null, 'offset': null, 'units': '' }]
  },
  'dive_summary': {
    'num': 268,
    'fields': [{
      'name': 'reference_mesg',
      'number': 0,
      'type': 'mesg_num',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'reference_index',
      'number': 1,
      'type': 'message_index',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'avg_depth',
      'number': 2,
      'type': 'uint32',
      'scale': null,
      'offset': 0,
      'units': 'm'
    }, {
      'name': 'max_depth',
      'number': 3,
      'type': 'uint32',
      'scale': null,
      'offset': 0,
      'units': 'm'
    }, {
      'name': 'surface_interval',
      'number': 4,
      'type': 'uint32',
      'scale': null,
      'offset': 0,
      'units': 's'
    }, {
      'name': 'start_cns',
      'number': 5,
      'type': 'uint8',
      'scale': null,
      'offset': 0,
      'units': 'percent'
    }, {
      'name': 'end_cns',
      'number': 6,
      'type': 'uint8',
      'scale': null,
      'offset': 0,
      'units': 'percent'
    }, {
      'name': 'start_n2',
      'number': 7,
      'type': 'uint16',
      'scale': null,
      'offset': 0,
      'units': 'percent'
    }, {
      'name': 'end_n2',
      'number': 8,
      'type': 'uint16',
      'scale': null,
      'offset': 0,
      'units': 'percent'
    }, {
      'name': 'o2_toxicity',
      'number': 9,
      'type': 'uint16',
      'scale': null,
      'offset': 0,
      'units': 'OTUs'
    }, {
      'name': 'dive_number',
      'number': 10,
      'type': 'uint32',
      'scale': null,
      'offset': 0,
      'units': ''
    }, {
      'name': 'bottom_time',
      'number': 11,
      'type': 'uint32',
      'scale': null,
      'offset': 0,
      'units': 's'
    }, { 'name': 'timestamp', 'number': 253, 'type': 'date_time', 'scale': null, 'offset': 0, 'units': 's' }]
  }
};

export default MsgDefs;
